Traceback (most recent call last):
  File "/Users/ar/work/ud-tools/validate.py", line 16, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
